name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main # Checkout the repository content to github runner

      - name: Set up .NET Core # For more information on the setup-dotnet action, visit
        uses: actions/setup-dotnet@v1 # Set up .NET Core SDK
        with:
          dotnet-version: 6.0.x # SDK version to use

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

      - name: Create the Package
        run: dotnet pack --configuration Release

      - name: Publish
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
